### ISSUE TITLE
b/bmsy values MEDITERRANEAN and BS stocks

### ISSUE THREAD

**Issue by chatoosio** [ramadmin/RLSADB#10]
B/Bmsy values from model fits seem extremely optimistic and need serious revision.

**Comment by kurota** [comment]
As I reported for each stock in this list, B/Bmsy of Japanese small pelagic seem pessimistic. The reason of this contrast among stocks might be worth exploring.

**Comment by ramadmin** [comment]
This should get resolved with the upcoming new production model fitting method/protocol.
