### ISSUE TITLE
West African sole stock not deprecated?

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#102]
SOLECWAGAB-COD is listed as Deprecated, and its former name is SOLECWASG3.

Under the 2018 report for demersal south subgroup, the stock is linked to countries Nigeria, Cameroon, Equatorial Guinea, with Nigeria having greatest catches.
http://www.fao.org/fi/static-media/MeetingDocuments/CECAF/CECAF-SSC8/Ref.7e.pdf

In RAM, the primary_country for this stock is listed as Nigeria (consistent with report above), but the labels in the stockid and stocklong suggest a different set of countries, from Gabon through Congo DR.

The assessment of this stock is based on an older report, "FAO West African Demersal Stocks.pdf", with no URL.

Maybe between that older report and the 2018 report, the definition of SG3 changed, which is why the range of countries included changed (I'm not sure).

However, either way, what other stock makes this stock deprecated? The only other one close by seems to be SOLECWAAGO, but wouldn't that one be specific to Angola, so not overlapping?

**Comment by ramadmin** [comment]
Since the West African stocks are so prone to stock area changes, when a new set of updates for a region/taxonomic grouping are imported I treat the last import as deprecated unless I see the same area/species.

**Comment by mcmelnychuk** [comment]
That makes sense if a new set of updates covers all of the stocks that were in all previous updates, but what if it doesn't? It's not certain that all stocks in the region will be assessed in each report released. If there are stocks that were assessed in a previous document but aren't covered in a more recent document, shouldn't we still include the latest available assessment for each of those individual stocks? 
This also applies to issue 107

**Comment by ramadmin** [comment]
This has been resolved with RAM v4.50. The stock has been re-added since there wasn't any overlap as initially expected.
