### ISSUE TITLE
F values for 2 west coast US stocks

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#104]
from Olaf Jensen and Rujia Bi:
Two West Coast stocks are distinct outliers and the differences are so
large that it must be an error (see below).  Do you have any ideas about
what might have happened here?  Is F maybe defined differently between
the two subsequent assessments?
NWFSC-DKROCKPCOAST-1928-2011-STACHURA
2011 F = 0.0226
NWFSC-DKROCKPCOAST-1915-2015-SISIMP2016
2011 F = 0.408
AND
NWFSC-SABLEFPCOAST-1900-2011-STACHURA
2011 F = 0.037
NWFSC-SABLEFPCOAST-1900-2015-SISIMP2016
2011 F = 0.577

---
Given the magnitudes, I suspect the values from the 2015 are errors (not just the year indicated, the full time series).

Can you look into these two assessments, compare values with those in published assessment documents, and make any necessary corrections?

**Comment by ramadmin** [comment]
It looks like the F values from the older assessments were actually ER values. This has been fixed with upcoming RAM v4.495.
