### ISSUE TITLE
TAC for NZ paua stock(s)

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#105]
in RAMLDB v4.494 (model fits included).xlsx, example year 2014 for PAUANPAU5A, we see Cpair = 63.6, TAC = 63600, and TCbest = 64.4, all of which say they're in units of MT. TAC is in kg, because values around 64 MT are more reasonable:
 https://www.mpi.govt.nz/fishing-aquaculture/recreational-fishing/fish-species/paua/

Actions to take:
- correct this TAC time series for PAUANPAU5A (divide by 1000)
- check the original entry template for PAUANPAU5A. (It might have been a special template of NZ time series for TAC, Cadv, and Cpair). If the error is present there, then check the other templates that were submitted in the same batch in case any other stocks have similar errors of time series in kg instead of MT

**Comment by ramadmin** [comment]
This has been fixed.
