### ISSUE TITLE
West African scad stock not deprecated?

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#107]
another one to check:

FSCADNWA is noted as deprecated, but it doesn't seem as if anything has taken its place. There are no other assessments for any Caranx species, and the only other scad stock is SCADSPPCWAGNB-LBR, but that covers a non-overlapping set of other countries. 
Or was it deprecated because of issues with the assessment?

**Comment by ramadmin** [comment]
Since the West African stocks are so prone to stock area changes, when a new set of updates for a region/taxonomic grouping are imported I treat the last import as deprecated unless I see the same area/species.

**Comment by ramadmin** [comment]
This has been resolved with RAM v4.50. The stock has been re-added since there wasn't any overlap as initially expected.
