### ISSUE TITLE
Likely unit errors in Bdiv and failure of QAQC checks

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#108]
1) There are at least three US stocks that have ratios of BdivBmsypref which probably reflect unit mismatches in numerator and denominator, or else mistakes in one or the other:
BUTTERGOMCHATT
QUAHATLC
POPERCHPCOAST
Values of ratios have magnitudes >1000 or <0.001.

2) These above errors were identified during spotchecks, they are not necessarily the only ones with problems. These were part of the 2021 SIS data extract. Were the QAQC checks not conducted when the data were extracted? If they were conducted, how did these ratios get through the checks?

**Comment by ramadmin** [comment]
There is now a div check as part of the data importing qaqc process so these should be identified in the future.
