### ISSUE TITLE
changes to herring west of Scotland/Ireland stocks

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#109]
two issues:

- HERRVIa should now be deprecated. The northern part of 6a used to be assessed separately, but as of 2016, advice is provided for the combined area under stock 6a.7bc (HERRVIaVIIbc)
- HERRVIaVIIbc should have "...6a..." in the stocklong instead of "...5a..."

**Comment by ramadmin** [comment]
This has been resolved with RAM v4.50, the suggested changes were implemented.
