### ISSUE TITLE
B reference points to check

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#110]
DFO-PAC-PERCHQCI-1939-2017-ASHBROOK
Check SSBmgt: seems incorrect, value is << SSBmsy and <<SSBlim

NWFSC-ESOLEPCOAST-1876-2007-BRANCH
Check SSBlim > SSBmsy (slightly unusual; check both values)

SARDI-SARDWSE-1992-2017-MOESENEDER
Check SSBlim > SSBmsy (slightly unusual; check both values)

CSIRO-WAREHOUESE-1986-2008-MOESENEDER
Check SSBlim > SSBmsy (unexpected; check both values)

CSIRO-WAREHOUWSE-1986-2008-MOESENEDER
Check SSBlim > SSBmsy (unexpected; check both values)

**Comment by ramadmin** [comment]
This has been resolved with RAM v4.50. The data was checked over and any errors were corrected.
