### ISSUE TITLE
SSB units for BMDOGVI

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#111]
For WGEF-BMDOGVI-VII-2001-2018-ICESIMP2021, according to advice report, SSB units are not MT, they’re kg/tow.

Not sure if this may affect other assessments of this stock and/or other ICES stocks. Is there any indication given in the ICES data download that the units may have been mixed up?

**Comment by ramadmin** [comment]
This has been resolved with RAM v4.50. The units were incorrect and have been updated.
