### ISSUE TITLE
Pollachius virens in ICES areas

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#113]
This species goes by 'saithe' in Europe (unlike in Canada/US), and it's always confusing for it to come up as 'pollock' in stocklong and common name. Even if stockid's are kept as POLL... for legacy reasons, and even if common name 'Pollock' is kept for consistency with latin name, can the stocklong change to 'Saithe' for the four European stocks (including all their historical assessments)?

**Comment by ramadmin** [comment]
This has been resolved with RAM v4.50. The suggested changes were implemented.
