### ISSUE TITLE
name change for HERRQCI

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#114]
We should probably change at least the stocklong, and probably also the stockid, for a BC herring stock. Its name changed a long time ago already.

HERRQCI -> HERRHG
'Pacific herring Queen Charlotte Islands' -> 'Pacific herring Haida Gwaii'

**Comment by ramadmin** [comment]
This has been resolved with RAM v4.50. The suggested changes were implemented.
