### ISSUE TITLE
making .data items numeric matrices with consistent columns

### ISSUE THREAD

**Issue by RayHilborn** [ramadmin/RLSADB#13]
I think it would be far better if the r objects of the .data type were numeric matrices

Also for all of those matrices it would be good if the columns were the same -- so have every current stock assessment as a column even if it doesn't ever have the kind of data

Ray

**Comment by ramadmin** [comment]
The main data objects should now be numeric (but still have the same rownames and colnames).

In the next version I will add empty columns for stocks without data for a given object.
