### ISSUE TITLE
West coast rock lobster South Africa

### ISSUE THREAD

**Issue by Carryn** [ramadmin/RLSADB#17]
These comments apply to Area 1 and 2, Area 3 and 4, Area 5 and 6, Area 7, Area 8
Stock ID: CRLOBSTERSA12, CRLOBSTERSA34, CRLOBSTER56, CRLOBSTER7, CRLOBSTER8

i)	Remove Current Value of 0 for SSB in the Time Series table. (While egg production is provided, SSB isn't so a zero doesn't make sense in this table)
ii)	For WCRL only the male biomass >75mm is modelled as the equivalent for total biomass.  Thus in plots you can use B75m for TB.  Any change you can replace the "TB-MT" title on the graph with "B75-MT"?  Update with the latest (1910-2014) assessment rather than that up to 2012 only.
iii)	You can plot egg production instead of the SSB curve, again using latest (1910-2014) assessment rather than up to 2012 only.  Any chance you can replace the “SSB-relative” title on the graph with “EggProd-relative”, or do the graph titles need to remain consistent between all stocks?
iv)	Update the ER-calc-ratio v year plot from the (1910-2012) assessment to that provided with the latest (2014) assessment.  Please confirm you are using the files Johnston-CRLOBSTERSA12-2015_APR2016.xlsx (and similarly for other areas) and not the original ones submitted that didn't have the "APR2016" on the end of the name?
v)	The available TAC, Cpair, Cadvised time series has been provided with the SNAP attributes template – could you copy that across?

**Comment by ramadmin** [comment]
i.) Implemented.

ii.) We have parameters that specify additional info about the time series, ie for these stocks the TB-NOTE parameter indicates that the time series is composed of "Unfished male biomass above 75mm carapace length."

iii.) We try to keep the titles consistent.

iv.) Implemented.

v.) Which file is that?

**Comment by ramadmin** [comment]
The TAC set of data has been added.
