### ISSUE TITLE
Deep Water cape hake South Africa

### ISSUE THREAD

**Issue by Carryn** [ramadmin/RLSADB#18]
Stock ID DEEPCHAKESA

i) Remove the Fmsy value of 0.35 from the table (taken from previous 2013 assessment).  That was a Umsy (or ERmsy) target provided, which has been updated and is incorporated in ERmsy value in same table.
ii) Update TB plot to 2015 assessment (current plot says 1917-2013 assessment used)

**Comment by ramadmin** [comment]
The parameter ID has been updated and the plot bug has been fixed.
