### ISSUE TITLE
STOCK: Canary rockfish Pacific coast

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#2]
Units problem: SSBmsy in MT but SSB time series in eggs

**Comment by mcmelnychuk** [comment]
Daniel, can you please add some rules to check that units match before pairing up a time series and a reference point? (That was not an exhaustive search, there could be other stocks with the same issue.)

**Comment by ramadmin** [comment]
The 2011 assessment had SSB with MT and the 2015 assessment with eggs. There is a bug in the newer SSBmsy in eggs not being displayed in the views, but there is no ratio time series being generated from data of different units. This will be fixed in the coming version.

**Comment by ramadmin** [comment]
This issue has been fixed.
