### ISSUE TITLE
Patagonian toothfish South Africa Subantarctic Prince Edward Islands

### ISSUE THREAD

**Issue by Carryn** [ramadmin/RLSADB#22]
Stock ID: PTOOTHFISHPEI
i) ERmsy wasn't provided in the 2013 or 2015 assessments.  It looks what has been used is Fmsy to compare with current ER in the table and for the time series plot. In that case, please update with Fmsy from the 2015 assessment which is 0.12.
ii) Please update TB plot from 1960-2013 with the new assessment up to 2015

**Comment by ramadmin** [comment]
This plot bug has been fixed.
