### ISSUE TITLE
STOCK: Alaskan Pollock Pacic Coast of Japan

### ISSUE THREAD

**Issue by kurota** [ramadmin/RLSADB#3]
Graphic issue: In RussiaJapanSummaryFile.pdf, the scale of Y-axis of TB figure might be wrong. TBmsy of this stock is 729,113MT, but TBmsy in the figure looks to be around 1,000,000MT. The same issue was found in other stocks such as Round herring Tsushima Strait and Japanese Spanish mackerel Inland Sea of Japan.

**Comment by ramadmin** [comment]
The display of the plots and reference points has been improved so this should be resolved.
