### ISSUE TITLE
STOCKS: US west coast lingcod

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#31]
added from email:
---
Thanks -- for this release of RAM we will stick to the 2009 two area assessment.

On Fri, Dec 23, 2016 at 7:53 AM, Melissa Haltuch - NOAA Federal <melissa.haltuch@noaa.gov> wrote:

    Hi Guys,

    Yes, the correct 2009 assessment is the two area, north/south, model. The new 2017 model will be available after Sept. 2017.

    Cheers,
    m

    On Thu, Dec 22, 2016 at 3:36 PM, Jason Cope <copejasonm@gmail.com> wrote:

        Hi Ray,

        Yes, I would definitely use the 2009 north and south model outputs (though the southern one is sketchier than the northern model) over the 2005 coastwide model.
        Or wait until Melissa does the new one this summer!

        -Jason

        On Thu, Dec 22, 2016 at 3:22 PM, Ray Hilborn <hilbornr@gmail.com> wrote:

            Jason:

            What we got from SIS is a coastwide assessment that goes through 2009.  I take it we should use the N and S assessments?

            Ray

            On Thu, Dec 22, 2016 at 10:05 AM, Jason Cope <copejasonm@gmail.com> wrote:

                Hi Ray,

                The last assessment, in 2009, was only north and south-- no coastwide model was presented as far as I can tell.
                Here is the assessment document link with the north and south assessments.
                http://www.pcouncil.org/wp-content/uploads/Lingcod_Assessment_2009_Final_SAFE_version.pdf

                The 2005 assessment was coastwide. 
                Not sure why SIS would have a coastwide model, but possibly a leftover from 2005? Maybe management combined the north and south into a coastwide model? I did that for the Council for the California assessment using the results from separate northern and southern California models (instead of using the coastwide model I also put together, but argued neglected important spatial considerations captured in the north and south models). 
                If the coastwide SIS model is just the simple addition of the north and south model, then that would explain it.

                Stacey Miller (stacey.miller@noaa.gov) would be the best person to clarify why a coastwide model would be present in SIS.

                -Jason

                On Thu, Dec 22, 2016 at 6:48 AM, Ray Hilborn <hilbornr@gmail.com> wrote:

                    Melissa and Jason:

                    We have recently done an update of RAM Legacy from the SIS data base, and in doing some quality control I find that there are three Lingcod assessments,  one for North, one for South and one that apparently covers the whole coast.

                    From what I can tell the most recent assessment covers the whole coast and the north and south assessments are older versions.

                    Does this seem correct?

                    Ray

**Comment by ramadmin** [comment]
The combined-area version has been removed.
