### ISSUE TITLE
Southern spiny lobster South Africa South Coast

### ISSUE THREAD

**Issue by Carryn** [ramadmin/RLSADB#35]
Please find attached updated template for SCRL, now including:
SSBmgt-type
SSBmgt
SSB0

[Johnston-SSLOBSTERSASC-2015updated.xlsx](https://github.com/ramadmin/RLSADB/files/708219/Johnston-SSLOBSTERSASC-2015updated.xlsx)

**Comment by ramadmin** [comment]
Implemented.
