### ISSUE TITLE
sexes of biomass time series

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#40]
Two stocks have possible typos and possible errors for bioid's (in bioparams table) associated with sexes of biomass time series.
NWFSC-BLACKROCKNPCOAST-1914-2006-BRANCH
NWFSC-ESOLEPCOAST-1876-2007-BRANCH

bioid = STB-SEX-sex, which is different from the typical values SSB-SEX-sex or TB-SEX-sex.

for assessid = NWFSC-BLACKROCKNPCOAST-1914-2006-BRANCH and bioid=STB-SEX-sex, biovalue=0 and bionotes=females , but instructions are that 0 = both sexes. One of these (0 or females) is incorrect?

**Comment by ramadmin** [comment]
Resolved.
