### ISSUE TITLE
ranges formatted as text

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#41]
Values that take ranges are having the date format assigned when exporting to Excel verisions. This affects things like ages of TB time series, ages of SSB time series, some bioparams.

These can have text formatting rather than date formatting applied by preceding the value by a single appostrophe, or by enclosing the range in quotation marks.

All such fields that can take ranges should be corrected so the values don't show as dates.

**Comment by ramadmin** [comment]
Implemented using the format x to y instead of x-y.
