### ISSUE TITLE
removal of Cpair,TAC,Cadvised

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#43]
These stocks should have Cpair, TAC, and Cadvised time series, notes, and bioparam identifiers removed from RAM:

New Zealand ling New Zealand Area LIN 72 (suggested by Pamela Mace)

New Zealand ling New Zealand Area LIN 7WC - WCSI (suggested by Pamela Mace)

New Zealand snapper New Zealand SNA 1 Bay of Plenty and Hauraki Gulf	(TACCs are only for both SNA 1 stocks pooled, not for individual stocks. Confirmed by Pamela Mace)

New Zealand snapper New Zealand SNA 1 east Northland (TACCs are only for both SNA 1 stocks pooled, not for individual stocks. Confirmed by Pamela Mace)

**Comment by mcmelnychuk** [comment]
also, TAC should be removed for these stocks. They share a TAC, it's not partitioned into individual stocks:

Hoki Eastern New Zealand

Hoki Western New Zealand

both confirmed by Pamela

**Comment by mcmelnychuk** [comment]
note the TAC-GA applies to both hoki and the two ling from area 7 above, but in both cases that's too error-prone because someone will link up the pooled stock TACs with the individual stock catches and calculate incorrect ratios. We'll keep track of pooled stocks externally.

**Comment by ramadmin** [comment]
Implemented.
