### ISSUE TITLE
Cpair and TAC for 2 NZ stocks?

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#44]
Daniel, can you please check if Cpair and TAC were in the submission forms for these stocks, but somehow didn't make it into the database? I have it recorded that they were in the past submitted:
Red rock lobster New Zealand area CRA3
Red rock lobster New Zealand area CRA5

**Comment by mcmelnychuk** [comment]
see email from me August 26 2016 containing NZ red rock lobster input forms from Pamela Mace & Paul Starr. It looks like these two stocks were perhaps not inputted but the others were?

**Comment by ramadmin** [comment]
These are now included.
