### ISSUE TITLE
missing stocks?

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#46]
these seems to be missing from the snapgroupfile associated with upcoming 4.15:

PANCHCHVX	Peruvian Anchoveta Chile Region V-X
PANCHNCH	Peruvian Anchoveta North Chile
PANCHSCH	Peruvian Anchoveta South Chile

the three anchoveta may have been replaced by these (?):
PANCHCCH	Peruvian Anchoveta Central Chile
PANCHCSCH	Peruvian Anchoveta Central-Southern Chile
PANCHNCHSP	Peruvian Anchoveta Northern Chile Southern Peru

Or have the above stocks been dropped for other reasons?

**Comment by ramadmin** [comment]
Correct, there were a lot of stock name/area updates with that version for that region.
