### ISSUE TITLE
remove Chilean horse mackerel

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#47]
following up on Ana's comment:
- CHING uploaded a stock called HMACKCH (Trachurus trachurus). This seems to be a mistake. The report cited in the old template is for "jurel" (CHTRACCH) and the catches in the two old templates (CHTRACCH and HMACKCH)  are the same. So please remove HMACKCH and only keep  CHTRACCH.

**Comment by ramadmin** [comment]
Implemented.
