### ISSUE TITLE
The most recent data for 8 Japanese stocks

### ISSUE THREAD

**Issue by kurota** [ramadmin/RLSADB#52]
Walleye pollock Pacific Coast of Japan [APOLLPJPN]
Spotted mackerel East China Sea [BMACKECS]
Spotted mackerel Pacific Coast of Japan [BMACKPJPN]
Chub mackerel Tsushima Strait [CMACKTSST]
Japanese anchovy Pacific Coast of Japan [JANCHOPJPN]
Japanese anchovy Inland Sea of Japan [JANCHOSETO]
Japanese anchovy Tsushima Strait [JANCHOTSST]
Round herring Tsushima Strait [RHERRTSST]

For the above 8 Japanese stocks, two datasets that include up to 2013 [FAJ-xxx-2013-JPNIMP2016] and 2014 [FAJ-xxx-2014-KUROTA] are registered in RAM4.15. I'd like to designate the 2013 dataset rather than the 2014 dataset as the “most recent” version for these stocks. Please change the "most recent" flag for the 8 stocks in RAM and/or do something necessary to hide the 2014 dataset even for the "model fits included" database (or simply remove the 2014 dataset from RAM).

This is because the 2013 dataset includes original reference points (SSBmsy and Umsy) that we estimated, while the 2014 dataset does not. Also for other Japanese stocks, the 2013 dataset only is currently registered in RAM. Therefore, by using the 2013 dataset for our analysis, we can keep consistency among Japanese stocks and avoid using different reference points estimated by a production model, though we lose the one-year data for 2014.

**Comment by ramadmin** [comment]
Implemented.
