### ISSUE TITLE
double check select U and B ratios

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#62]
in version 4.3:

average UdivUmsypref seems unrealistically high:
West coast rock lobster South Africa Areas 1-2
Hogfish Southeast Florida
Atlantic menhaden Atlantic

average BdivBmsypref seems unrealistically high:
Jackass morwong Southeast Australia
School whiting Southeast Australia

**Comment by ramadmin** [comment]
These have been addressed in the current version (v4.40).
