### ISSUE TITLE
ICES IIIa plaice removal

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#63]
There was an old assessment for area IIIa plaice which is currently in the ICES SP model output package. Since that old assessment, the area has been split and portions have been included with other assessment units:
subdivisions 21-23
North Sea & IIIa

Those current assessment units are already included in RAM and in the SP model outputs. It's just the old IIIa assessment that should be removed from the RAM views tables, and not included in the ICES SP model results.

Can you check the "asmtmostrecent" variable, views tables, and the stock split/merge history list, and adjust those accordingly?

**Comment by ramadmin** [comment]
This was resolved, and is present in the stock split/merge history file.
