### ISSUE TITLE
various region and country checks

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#64]
Here are various issues from stocks, assessments, or areas tables. It's possible that some of these are intentional, but I think most of them are minor errors that could be corrected:

- country==multinational and country==Multinational will be treated as separate categories when used as factors. Can you make it all consistent, either lowercase or sentence case across all stocks?

- stocklong==Atlantic cod NAFO 5Zjm
areaid==Canada-DFO-5Zjm
region==US East Coast
country==Canada
This may be the joint TRAC stock assessment for the small eGB stock, which I think is nested within the larger US northeast assessment for Georges Bank cod. areaid, region, and country should probably all be consistent with one another, either Canada or US, whatever makes most sense.

- stocklong==Albacore tuna North Pacific
areaid==Multinational-ISC-NPAC
region==US West Coast
country==Multinational
region should be changed to "Pacific Ocean"

- stocklong==Atlantic cod NAFO Subarea 1 (inshore)
areaid==multinational-ICES-1IN
region==Europe non EU
country==multinational
This is an ICES assessment, but it's for a stock located in NAFO waters, west of Greenland. The areaid should be changed to ...NAFO... instead of ...ICES... To be consistent with other NAFO stocks, we might want to consider this as region==Canada East Coast (although other arguments could support leaving it as region==Europe non EU, especially for those off Greenland)

- stocklong==Greenland halibut NAFO 01ABCDEF
areaid==multinational-NAFO-01ABCDEF
region==European Union
region would be more accurate as either Europe non EU or as Canada East Coast, keeping it consistent with other NAFO stocks off Greenland

- stocklong==Redfish species NAFO 1
areaid==multinational-NAFO-1
region==European Union
region would be more accurate as either Europe non EU or as Canada East Coast, keeping it consistent with other NAFO stocks off Greenland

- stocklong==Beaked Redfish Areas V-XII-XIV and NAFO Subareas 1-2
areaid==multinational-ICES-1-2-V-XII-XIV
region==European Union
region would be more accurate as Europe non EU
would an areid of multinational-ICES-V-XII-XIV-NAFO-1-2 be clearer?

**Comment by ramadmin** [comment]
These are resolved in the current version (v4.40).
