### ISSUE TITLE
stocks with missing catch data?

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#66]
For the following stocklongs, the number listed is the number of years for which there are Udiv and/or Bdiv values, but no TCbest values in the same year. There is probably a good explanation for most of these (e.g. catch in numbers, not MT, or else Bdiv time series extend back earlier than recorded catch data), but for some of them, catch should be in MT and it's surprising they have so much missing catch data. 
I'm only listing the ones with >=5 years of missing TCbest data.
I'm only listing the subset of stocks in the SNAPP analysis.

Could you look into these stocks and check that there are good reasons for missing catch data?

Bonnethead shark Atlantic 
                                                         62 
                                   Blacknose shark Atlantic 
                                                         60 
                                     Sandbar shark Atlantic 
                                                         50 
                                     Atlantic cod Irish Sea 
                                                         40 
                        Pacific chub mackerel Pacific Coast 
                                                         33 
                                 Red king crab Norton Sound 
                                                         33 
                 Striped bass Gulf of Maine / Cape Hatteras 
                                                         31 
                       Orange roughy Northwest Chatham Rise 
                                                         30 
                                  Lingcod Strait of Georgia 
                                                         26 
           Striped marlin Western and Central North Pacific 
                                                         22 
                                   Blue Crab Chesapeake Bay 
                                                         21 
                    Walleye pollock Northern Sea of Okhotsk 
                                                         21 
                         Blue Grenadier Southeast Australia 
                                                         19 
           Greenland turbot Bering Sea and Aleutian Islands 
                                                         18 
                                   South Pacific Hake Chile 
                                                         18 
                                Southern blue whiting Chile 
                                                         18 
                         Walleye pollock Eastern Bering Sea 
                                                         15 
                                   Sea scallop Georges Bank 
                                                         12 
                             Walleye pollock Gulf of Alaska 
                                                          8 
                              Pacific sardine Pacific Coast 
                                                          6 
                                  Red Shrimp Northern Spain 
                                                          6 
                                      Sardine Gulf of Lions 
                                                          6 
                                Greenland halibut NAFO 4RST 
                                                          5

**Comment by ramadmin** [comment]
No issues were found. The lack of data comes from either short time series or catch in units of individuals.
