### ISSUE TITLE
taxonomy table corrections for version 4.4

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#67]
hi Daniel,
I'm attaching a file with a few updates to the taxonomy table, all highlighted in red. These correspond to the latest accepted names in WoRMS. There are two rows that can now be deleted as they're duplicates of existing rows.

[RAM 4.4 taxonomy corrections.xlsx](https://github.com/ramadmin/RLSADB/files/2104300/RAM.4.4.taxonomy.corrections.xlsx)

Moving forward, it might be worth having both "assessment/original" and "accepted" versions in the taxonomy tables of the following variables:
phylum, class, order, family, genus, species, scientificname

They could be named something like "phylum.assess" (or "phylum.orig") and "phylum.acc" to distinguish them. That way whenever there are updates like this to make, the originals can remain unchanged and just the updated changes in WoRMS can change.

Mike

**Comment by ramadmin** [comment]
The taxonomy table has been updated.
