### ISSUE TITLE
U or catch values of 0

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#72]
Daniel, would you mind going through the values of catch (TCbest, TC, TL) and U (ERbest, ER, F, and direct ER/ERxxx or F/Fxxx) to check for values of exactly 0, and check for their legitimacy? If they're in the earliest part of the time series or if they're during a moratorium they should be considered legitimate, but there may be some that are mistakes, particularly in the final year.

For example, there's a 0 value for RROCKLOBSTERCRA3 in the final year, which is likely a mistake as there aren't any catch data in the same year and B is > Bref.

**Comment by ramadmin** [comment]
Checked over the time series and that stock was the only obvious error and has been resolved.
