### ISSUE TITLE
South Africa rock lobster and reference point overrides

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#73]
hi Daniel, I think there are still issues with SA rock lobster stocks. I'm looking at version 4.41, the later one you released Aug. 28 after tweaks for South Africa stocks.  

The proxy target rebuilding points should not be used for "mgt" reference points, as they're for rebulding purposes only and far more conservative than what the targets would be at desirable biomass levels. These are leading to very high U/Umgt especially.

For the 5 CRLOBSTER stocks, the current values of TBmgt and ERmgt should be removed from both the assessment-only and the model-fit versions. 
(Maybe wait until I confirm with Carryn, emailing today 2018-11-23)

The values of TBmsybest of 0.368*B0 can remain in the model-fit version. 
I note that these are only listed for TBmsybest, and not for TBmsy. Perhaps it's worth generalizing this approach for other cases where we'll manually override the default reference points? Maybe we could consid some kind of a "manual" bioid for reference points (e.g. TBmsy-manual) which could appear only in the model fit version, and could be at the top of the preference hierarchy for reference points?

**Comment by ramadmin** [comment]
Addressed in previous version.
