### ISSUE TITLE
additions to Stock Change History file

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#74]
I suspect these stocks should be added to the "Stock Change History" file now that updated stock definitions are in the database:
- Blue Grenadier Southeast Australia to Blue grenadier New South Wales to Western Australia
- Herring ICES 30 to Herring Subdivisions 30-31
- Herring ICES 31 to Herring Subdivisions 30-31

**Comment by ramadmin** [comment]
I'll update the stock change history file with these and other changes in the v4.45 release.

**Comment by ramadmin** [comment]
This has been implemented.
