### ISSUE TITLE
areaid of LINGNEATL

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#75]
For the ling stock LINGNEATL the areaid should have areas I, II, and V removed so that there isn't confusion about this stock overlapping with three other ling stocks, LINGI-II, LINGVa, LINGVb. The assessment document is clear that LINGNEATL only covers areas VI-IX, XII, XIV, and divisions III.a and IV.a

**Comment by ramadmin** [comment]
Corrected.
