### ISSUE TITLE
stocks with missing UdivU or BdivB in timeseries table

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#77]
This was a series of spotchecks, not an exhaustive search. Based on mdl-fits version 4.44

PANCHPERUNC
- no values of UdivU in timeseries table even though there are ER time series and passing SP fits (Schaefer) for both IMARPE-PANCHPERUNC-1959-2008-HIVELY and IMARPE-PANCHPERUNC-1959-2016-HILBORN.

HMACKWA
- no values of BdivB in timeseries table even though there are TB time series and passing SP fits (Schaefer, empirical) for FAO-SPNWA-HMACKWA-1990-2010-CHING.

SNAPSAUSNSG
- no values of UdivU or BdivB in timeseries table even though there are ER and TB time series as well as passing SP fits (free) for SARDI-SNAPSAUSNSG-1983-2010-BANOBI.

SSSHRIMPSMA14
- no values of UdivU or BdivB in timeseries table even though there are ER and TB time series as well as passing SP fits (Schaefer) for DFO-SSSHRIMPSMA14-1987-2011-WATSON.

CRLOBSTERSA12
- no values of UdivU in timeseries table even though there are ER time series and passing SP fits (all models except Schaefer) for MARAM-CRLOBSTERSA12-1910-2012-Johnston.

SEELNSSA3
- no values of UdivU in timeseries table even though there are ER time series and passing SP fits (Fox, PTtax) for HAWG-SEELNSSA3-1983-2016-ICESIMP2016.

SARDSA
- no values of UdivU or BdivB in timeseries table even though there are ER and TB time series as well as passing SP fits (all models) for MARAM-SARDSA-1949-2015-deMoor.

SSLOBSTERSASC
- no values of UdivU in timeseries table even though there are ER time series and passing SP fits (all models) for MARAMARAM-SSLOBSTERSASC-1973-2014-Johnston.

**Comment by ramadmin** [comment]
This should be resolved with the prior spfit update.
