### ISSUE TITLE
Reference point values for 2 stocks in SIS

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#79]
Umsy values for these two stocks are showing as:

SEFSC-BLTILESATLC-1974-2011-SISIMP2016
0.000307

SEFSC-COBSATLC-1950-2011-SISIMP2016
0.000513

But assessment documents show they should be closer to FMSY = 0.146 for tilefish (in a newer assessment) and Fmsy=0.461 for cobia.

Can you check the assessment pdfs, confirm, and change the values in RAM? Those values were probably imported from SIS and were overlooked.

**Comment by ramadmin** [comment]
These values did not come from an assessment, they are calculated values using MSY and a SSBmsy converted to a TBmsy (so only present in model-fits version).

**Comment by mcmelnychuk** [comment]
Let's leave these for now and then check again after biomass conversion regressions are next updated

**Comment by mcmelnychuk** [comment]
Actually, can you just add the F time series and Fmsy values from the assessment documents for these two stocks?

**Comment by ramadmin** [comment]
This has been implemented with v4.49.
