### ISSUE TITLE
biomass for SPURDNEATL

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#80]
For WGEF-SPURDNEATL-1905-2016-ICESIMP2018, 
the TB-MT time series in RAM goes from 3.44E+05 in 1905 to 5.10E+04 in 2016.
The assessment document (Table 9.3.17.10) instead lists this as 1653940 in 1905 to 296104 in 2016.

The value for Bmsy (MSY Btrigger in terms of TB) is correct.

Any idea how the time series were imported incorrectly? Could that be SSB instead?

This was only a spotcheck; could this apply to other stocks also?

**Comment by ramadmin** [comment]
This has been resolved, and looked to be an issue only with this stock.
