### ISSUE TITLE
additions to RAMCore.rdata

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#81]
Could you add:

- taxgroup vector (similar to "Region" and "FisheryType", keeping order of stocks)
- catch/MSY matrix (called CvMSY, or other)
- catch/(mean catch) matrix (called CvMeanC, or other)
- possibly also a CvCpref, which for each stock would be a time series of CvMSY if available, otherwise CvMeanC

I see notes that "MCatch" is actually TCbest, is that true? (And it's a matrix.)  Is there potential confusion with mean catch?

**Comment by ramadmin** [comment]
These have been added, and there is now documentation describing the RAMCore objects.
