### ISSUE TITLE
catch units 2 Canadian herring stocks

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#84]
For the following two stocks, TC values are off by several orders of magnitude, and/or the units are not MT:
DFO-QUE-HERR4RFA-1971-2003-PREFONTAINE
DFO-QUE-HERR4RSP-1963-2004-PREFONTAINE

This may be a known problem as these TC series do not feed into TCbest values, but they should be corrected as needed in the TC series (after which they could feed into TCbest).

**Comment by ramadmin** [comment]
This has been resolved.
