### ISSUE TITLE
check ts and BRPs for CHTRACCH

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#87]
There is likely a units problem or a mixup with SSB and TB. The fishery barely started developing until the 1970s (catch and U increasing from near 0 before that), but SSBdivSSBmsy-est-dimensionless starts off <0.5 in 1970. It's possible this could be environmentally-driven, but best to check.

**Comment by ramadmin** [comment]
Checked over the assessment and could not find any issue.
