### ISSUE TITLE
ICES reference point types not importing?

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#88]
I see some reference point types that are in some ICES assessments but that were not a part of the database import. For example:
https://doi.org/10.17895/ices.pub.4419
contains HR_MSY, HR_mgt (HR is equivalent to ER), but these are not contained in the bioparams for either NWWG-CODICE-1952-2017-ICESIMP2018 or NWWG-CODICE-1952-2018-ICESIMP2018.

Haven't checked for other ICES stocks, but I don't see any bioid = HR_..., so if they're available for other stocks they're similarly not making it into RAM
Are HR_... reference points available in the database but not making it into the import?

**Comment by ramadmin** [comment]
This is due to some inconsistency in the display of HR with the stocks that have it. This has been resolved for HR, but its possible other data types are present in the assessment that did not make it to data dump.
