### ISSUE TITLE
SP fits to check

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#92]
Daniel, could you please check model fits 1-6 for each of the two following assessid's?
WGCSE-WHITVIIa-1980-2016-ICESIMP2018
WGSSDS-SOLECS-1970-2011-NEUBAUER

The fits all pass, but values of mean ER/ERmsy SPmod seem very small, leading to large values of 
equivalent Fmsy SPmod. 

Please check model fits against time series of ER and/or F to see what might be so unusual.

**Comment by ramadmin** [comment]
These issues have been resolved with RAM v4.60, they were the result of ER time series errors.
