### ISSUE TITLE
NAFO and ICES labels mixed up

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#95]
A few stocks to check:

1) COD1abdce | Gadus morhua | Atlantic cod | multinational-ICES-1abdce | Atlantic cod NAFO 1abdce
- this is presumably from NAFO area 1, which includes NAFO subareas 1A, 1B, 1C, 1D, 1E.
- stockid could have capitalization corrected for a,b,c,d,e
- areaid should be changed from ICES to NAFO, also correcting capitalization
- stocklong should have capitalization corrected for a,b,c,d,e

2) COD1IN | Gadus morhua | Atlantic cod | multinational-ICES-1IN | Atlantic cod NAFO Subarea 1   (inshore)
- this is also presumably from NAFO area 1. Not sure if there is an inshore/offshore designation
- areaid should be changed from ICES to NAFO

- could you check if (1) and (2) are actually the same stock, and if so merge in the records? These assessments are likely conducted by NAFO.

3) COD1f-XIV | Atlantic cod NAFO 1f   and ICES 14 | Gadus morhua | Atlantic cod | multinational-ICES-1f-XIV
- in stockid, stocklong, and areaid, it would be preferable if 'F' is capitalized
- can areaid handle '...NAFO-1F-ICES-XIV' (or '...NAFO-1F-ICES-14') ?

4) REDDEEPDP-1-2-V-XII-XIV | Beaked redfish ICES   5-12-14 and NAFO Subareas 1-2 (deep) | Sebastes mentella | Beaked redfish | multinational-ICES-DP-1-2-V-XII-XIV
- can areaid handle '...NAFO-1-2-ICES-V-XII-XIV-DP' (or '...NAFO-1-2-ICES-5-12-14-DP') ?

5) REDDEEPSH1-2-V-XII-XIV | Beaked redfish ICES   5-12-14 and NAFO Subareas 1-2 (shallow) | Sebastes mentella | Beaked redfish | multinational-ICES-SH-1-2-V-XII-XIV
- can areaid handle '...NAFO-1-2-ICES-V-XII-XIV-SH' (or '...NAFO-1-2-ICES-5-12-14-SH') ?

**Comment by ramadmin** [comment]
Will address with next version.

**Comment by ramadmin** [comment]
Getting fixed with RAM v4.494.
