### ISSUE TITLE
areaid for SPURDNEATL

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#98]
should add sub area 10 to areaid

Spurdog (Squalus acanthias) in subareas 1–10, 12, and 14 (the Northeast Atlantic and adjacent waters) 
https://www.ices.dk/sites/pub/Publication%20Reports/Advice/2020/2020/dgs.27.nea.pdf

**Comment by ramadmin** [comment]
Getting fixed with RAM v4.494.
